apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-notes-app-deployment
  labels:
    app: notes-app
  namespace: aks-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app
        image: abhisheksah05081998/notes-apps-k8s
        ports:
        - containerPort: 8000

