apiVersion: v1
kind: Service
metadata:
  name: my-notes-app-service
  namespace: aks-project
spec:
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

