kind: Job
apiVersion: batch/v1
metadata:
  name: demo-job
  namespace: abhi
spec: 
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: demo-job-pod
      labels:
        app: batch-task

    spec:
      containers:
      - name: batch-container
        image: busybox:latest
        command: ["sh" ,"-c" , "echo Hello Friends Myself Abhishek!  &&  sleep 10 "]
      restartPolicy: Never
