kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-persistencevolume
  namespace: abhi
  labels:
    app: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data
