kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-persistentvolumeclaim
  namespace: abhi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage

